### Home page
GET http://localhost:3001

### GET all notes
GET http://localhost:3001/api/notes

### Get a note for id
GET http://localhost:3001/api/notes/1

### Delete a note for id
DELETE http://localhost:3001/api/notes/2

### Crear un nueva nota
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Postman is good in testing backend",
  "important": true
}

### Prueba de error al crar una nueva nota con content type difernete a json
POST http://localhost:3001/api/notes
Content-Type: text/plain

{
  "content": "Postman is good in testing backend",
  "important": true
}